export enum GameEvents {
    StartGame = 'startGame',
    PlayerLeaveGame = 'playerLeaveGame',
    EndGame = 'endGame',
    GoodAnswerOnClick = 'goodAnswerOnClick',
    GoodAnswerOnFinishedTimer = 'goodAnswerOnFinishedTimer',
    BadAnswerOnClick = 'badAnswerOnClick',
    BadAnswerOnFinishedTimer = 'badAnswerOnFinishedTimer',
    QuestionChoiceSelect = 'questionChoiceSelect',
    QuestionChoiceUnselect = 'questionChoiceUnselect',
    GiveBonus = 'giveBonus',
    AddPointsToPlayer = 'addPointsToPlayer',
    NextQuestion = 'nextQuestion',
    PlayerAbandonedGame = 'abandonedGame',
    GameAborted = 'gameAborted',
    BanNotification = 'banNotification',
    ShowResults = 'showResults',
    SubmitQuestion = 'submitQuestion',
    BonusUpdate = 'bonusUpdate',
    SendResults = 'sendResults',
    SubmitQuestionOnClick = 'submitQuestionOnClick',
    SubmitQuestionOnFinishedTimer = 'submitQuestionOnFinishedTimer',
    RemoveSubmitOnAbandoned = 'removeSubmitOnAbandoned',
}
